# https://taskfile.dev/
version: "3"

vars:
  PYTHON: python3
  VENVS: .venvs
  TEST_ENV: .venvs/test
  LINT_ENV: .venvs/lint
  TEST_PYTHON: "{{.TEST_ENV}}/bin/python3"
  LINT_PYTHON: "{{.LINT_ENV}}/bin/python3"

env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  install:flit:
    status:
      - which flit
    cmds:
      - python3 -m pip install flit
  venv:test:
    status:
      - test -d {{.TEST_ENV}}
    cmds:
      - "{{.PYTHON}} -m venv {{.TEST_ENV}}"
  venv:lint:
    status:
      - test -d {{.LINT_ENV}}
    cmds:
      - "{{.PYTHON}} -m venv {{.LINT_ENV}}"
  install:test:
    sources:
      - pyproject.toml
    deps:
      - install:flit
      - venv:test
    cmds:
      - >
        flit install
        --python {{.TEST_PYTHON}}
        --extras=test,integrations
        --deps=production
        --symlink
  install:lint:
    sources:
      - pyproject.toml
    deps:
      - install:flit
      - venv:lint
    cmds:
      - >
        flit install
        --python {{.LINT_PYTHON}}
        --extras=lint,integrations
        --deps=production
        --symlink

  release:
    desc: generate and upload a new release
    deps:
      - install:flit
    cmds:
      - which gh
      - test {{.CLI_ARGS}}
      - cat walnats/__init__.py | grep {{.CLI_ARGS}}
      - rm -rf dist/
      - flit build
      - flit publish
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
      - gh release upload {{.CLI_ARGS}} ./dist/*

  pytest:
    desc: "run Python tests"
    cmds:
      - task: install:test
      - "{{.TEST_PYTHON}} -m pytest {{.CLI_ARGS}}"
  ruff:
    desc: "lint Python code"
    cmds:
      - task: install:lint
      - "{{.LINT_PYTHON}} -m ruff check --preview {{.CLI_ARGS}} ."
  ruff:fix:
    desc: "fix all possible ruff violations"
    cmds:
      - task: install:lint
      - "{{.LINT_PYTHON}} -m ruff check --preview --fix-only {{.CLI_ARGS}} ."
  mypy:
    desc: "check type annotations"
    cmds:
      - task: install:lint
      - "{{.LINT_PYTHON}} -m mypy {{.CLI_ARGS}}"
  yamllint:
    desc: "lint YAML files"
    cmds:
      - task: install:lint
      - "{{.LINT_PYTHON}} -m yamllint --strict {{.CLI_ARGS}} ."

  # groups
  format:
    desc: "run all code formatters"
    cmds:
      - task: ruff:fix
  lint:
    desc: "run all linters"
    cmds:
      - task: ruff
      - task: mypy
  test:
    desc: "run all tests"
    cmds:
      - task: pytest
  all:
    desc: "run all code formatters, linters, and tests"
    cmds:
      - task: format
      - task: lint
      - task: test
